FROM maven:3.5.2-jdk-8-alpine AS MAVEN_BUILD
COPY pom.xml /build/
COPY src /build/src/
WORKDIR /build/

RUN mvn package -DskipTests

FROM openjdk:8-jre-alpine
EXPOSE 8080
WORKDIR /app
COPY --from=MAVEN_BUILD /build/target/IoTHackathon.jar /app/
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=cloud", "IoTHackathon.jar"]
